spring:
  application:
    name: sample-spring-elasticsearch

  elasticsearch:
    rest:
      uris: http://183.98.182.142:9200
      username: elastic
      password: jigeum!

initial-import:
  enabled: false